# Generated by Django 2.2 on 2021-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='withdraw',
            field=models.TextField(default=''),
        ),
    ]
